# Add 'documentation' label to any changes within 'docs' folder or any subfolders
documentation:
- changed-files:
  - any-glob-to-any-file:
    - 'README.md'
    - '**/README.md'

# Add 'metric' label to any change to metric package.
metric:
- all:
  - changed-files:
    - any-glob-to-any-file: 'metric/**'

# Add 'feature' label to any PR where the head branch name starts with `feature/feat` or has a `feature/feat` section in the name
feature:
 - head-branch: ['^feature', 'feature', '^feat', 'feat']
