name: Go Packages Lint and Test
on:
  push:
    branches:
      - main

jobs:
  mertric-package-lint-test:
    uses: coderkakarrot/go-pkg-lib/.github/workflows/reusable-go-package-lint-test.yml@main
    with:
      target_directory: 'metric'
      golangci_lint_config_file: '../.golangci.yml'
#      threshold_file_coverage: 0
#      threshold_package_coverage: 74