name: Go Package Linting and Testing

on:
  workflow_call:
    inputs:
      target_directory:
        required: true
        type: string
      golangci_lint_config_file:
        required: true
        type: string

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58.1
          working-directory: ${{ inputs.target_directory }}
         # args: --config ${{ inputs.golangci_lint_config_file }}

      - name: Run unit test for
        run: make test/unit TARGET_DIR=${{ inputs.target_directory }}

      - name: Run codecoverage
        run: make test/unit/coverage TARGET_DIR=${{ inputs.target_directory }}