name: Go Package Linting and Testing

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      golangci_lint_config_file:
        required: true
        type: string

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        if: ${{ inputs.working_directory }}
        run: go mod download
        working-directory: ${{ inputs.working_directory }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58.1
          working-directory: ${{ inputs.working_directory }}
          args: --config=${{ inputs.golangci_lint_config_file }}
