name: Metrics Package
on:
  push:
    branches:
      - main

jobs:
  metric:
    uses: coderkakarrot/go-pkg-lib/.github/workflows/lint-test.yml@main
    with:
      target_directory: 'metric'
      golangci_lint_config_file: '../.golangci.yml'
      threshold_file_coverage: 0
      threshold_package_coverage: 0