name: Go Package Linting and Testing

on:
  workflow_call:
    inputs:
      target_directory:
        required: true
        type: string
      golangci_lint_config_file:
        required: true
        type: string
      go_version:
        required: true
        type: string
      golangci_version:
        required: true
        type: string

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ inputs.golangci_version }}
          working-directory: ${{ inputs.target_directory }}
          args: --config ${{ inputs.golangci_lint_config_file }}

      - name: Run unit test for ${{ inputs.target_directory }}
        run: make test/unit TARGET_DIR=${{ inputs.target_directory }}

      - name: generate unit test coverage
        run: make generate/unit/test/coverage TARGET_DIR=${{ inputs.target_directory }}

      - name: check test coverage
        run: make test/unit/coverage TARGET_DIR=${{ inputs.target_directory }}
