name: Release Notification to Slack (with slackify-markdown and webhook)

on:
  release:
    types: [published]
    tags:
      - 'metric/v*'
      - 'api/rest/v*'
      - 'pubsub/v*'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: print release notes
        run: |
            echo "${{ github.event.release.body }}"

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.3"


      - name: slackify markdown
        id: slackify-go
        run: |
          SLACKIFY_RELEASE_NOTES_MARKDOWN=$(go run ./internal/actions/cmd/slackmarkdown/main.go -release-notes="${{ github.event.release.body }}")
          echo $SLACKIFY_RELEASE_NOTES_MARKDOWN
          echo SLACKIFY_RELEASE_NOTES_MARKDOWN=$SLACKIFY_RELEASE_NOTES_MARKDOWN >> $GITHUB_ENV

      - name: print slackify release notes
        run: |
          echo "${{ env.SLACKIFY_RELEASE_NOTES_MARKDOWN }}"

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.26.0
        with:
          # For posting a simple message using incoming webhook
          payload: '{"text": "*:rocket: New Release: ${{ github.event.release.tag_name }} :rocket:* \n ${{ env.SLACKIFY_RELEASE_NOTES_MARKDOWN }}"}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
