name: Release Notification to Slack (with slackify-markdown and webhook)

on:
  release:
    types: [edited, published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Convert Release Notes to Slack Markdown
        id: slackify
        uses: LoveToKnow/slackify-markdown-action@v1
        with:
          text: ${{ github.event.release.body }}

      - name: check output
        run: echo "${{ steps.slackify.outputs.text }}"

      - name: check release context values
        run: echo "${{ github.event.release }}"

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # For posting a simple message using incoming webhook
          payload: |
            {
              "text": "🚀 New Release: *${{ github.event.release.tag_name }}*\n${{ steps.slackify.outputs.text }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
